#include "strings.h"

const char * const EFI_MEMORY_TYPE_STRINGS[] = {
        "EfiReservedMemoryType",
        "EfiLoaderCode",
        "EfiLoaderData",
        "EfiBootServicesCode",
        "EfiBootServicesData",
        "EfiRuntimeServicesCode",
        "EfiRuntimeServicesData",
        "EfiConventionalMemory",
        "EfiUnusableMemory",
        "EfiACPIReclaimMemory",
        "EfiACPIMemoryNVS",
        "EfiMemoryMappedIO",
        "EfiMemoryMappedIOPortSpace",
        "EfiPalCode",
        "EfiMaxMemoryType"
};

const CHAR16 * const EFI_ERROR_TYPE_STRINGS[] = {
        L"EFI_SUCCESS",
        L"EFI_LOAD_ERROR",
        L"EFI_INVALID_PARAMETER",
        L"EFI_UNSUPPORTED",
        L"EFI_BAD_BUFFER_SIZE",
        L"EFI_BUFFER_TOO_SMALL",
        L"EFI_NOT_READY",
        L"EFI_DEVICE_ERROR",
        L"EFI_WRITE_PROTECTED",
        L"EFI_OUT_OF_RESOURCES",
        L"EFI_VOLUME_CORRUPTED",
        L"EFI_VOLUME_FULL",
        L"EFI_NO_MEDIA",
        L"EFI_MEDIA_CHANGED",
        L"EFI_NOT_FOUND",
        L"EFI_ACCESS_DENIED",
        L"EFI_NO_RESPONSE",
        L"EFI_NO_MAPPING",
        L"EFI_TIMEOUT",
        L"EFI_NOT_STARTED",
        L"EFI_ALREADY_STARTED",
        L"EFI_ABORTED",
        L"EFI_ICMP_ERROR",
        L"EFI_TFTP_ERROR",
        L"EFI_PROTOCOL_ERROR",
        L"EFI_INCOMPATIBLE_VERSION",
        L"EFI_SECURITY_VIOLATION",
        L"EFI_CRC_ERROR",
        L"EFI_END_OF_MEDIA",
        L"EFI_END_OF_FILE",
        L"EFI_INVALID_LANGUAGE",
        L"EFI_COMPROMISED_DATA",
};
